# Generated by Django 4.2.10 on 2024-08-18 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_lessons_course_lessons_count_course_price_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='cash',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True, verbose_name='Денежные средства'),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course', verbose_name='Курсы'),
        ),
    ]
