# Generated by Django 4.2.10 on 2024-08-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_lessons_course_lessons_count_course_price_and_more'),
        ('users', '0002_balance_cash_balance_user_customuser_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='cash',
            field=models.PositiveIntegerField(default=1000, verbose_name='Денежные средства'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='courses.course', verbose_name='Курсы'),
        ),
    ]
