# Generated by Django 4.2.10 on 2024-08-18 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_balance_cash_alter_customuser_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.balance', verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Balance', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
