# Generated by Django 4.2.10 on 2024-08-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_lessons_count_and_more'),
        ('users', '0005_alter_customuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course', verbose_name='Курсы'),
        ),
    ]
