# Generated by Django 4.2.10 on 2024-08-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_lessons_course_lessons_count_course_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-id',), 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы и что-то по типу этого'},
        ),
    ]
