# Generated by Django 4.2.10 on 2024-08-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_options_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
