# Generated by Django 4.2.10 on 2024-08-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lessons_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students_count',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='Группа', max_length=250, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='group', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
