# Generated by Django 4.2.10 on 2024-08-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_group_users_group_students_alter_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
